version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: gptx_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Expose port for local development access (optional for production)
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "gptx_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: poetry run uvicorn gptx.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/gptx_db
      # Add other environment variables from your .env file here, e.g.:
      # WEB3_PROVIDER_URL: http://127.0.0.1:8545
      # SECRET_KEY: your-secret-key-change-in-production
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
